#!/usr/bin/env bash
function link_file {
    source="${PWD}/$1"
    target="${HOME}/${1/_/.}"

    info "Linking" "$source" "$target"


    if [ -e "${target}" ]; then
        if [ -L "${target}" ]; then
            unlink $target
        else
            mv $target $target.df.bak
        fi
    fi

    ln -sf ${source} ${target}
}

function unlink_file {
    source="${PWD}/$1"
    target="${HOME}/${1/_/.}"

    info "Unlinking" "$source" "$target"

    if [ -e "${target}.df.bak" ] && [ -L "${target}" ]; then
        unlink ${target}
        mv $target.df.bak $target
    fi
}


function info {
    echo "$1: '$3' --> '$2'"
}

if [ "$1" = "restore" ]; then
    for i in _*
    do
        unlink_file $i
    done
    exit
else
    for i in _*
    do
        link_file $i
    done

    CAT_LOCATION=$(which cat)
    echo -n "Updating .i3/config.."
    printf "###############\n#\n# DO NOT EDIT THIS FILE - EDIT ~/.i3/config.base instead\n#\n###############\n" > "$HOME/.i3/config"
    $CAT_LOCATION "$HOME/.i3/config.base" "$HOME/.i3-env/config" 2>/dev/null >> "$HOME/.i3/config"
    echo "done."
fi
